### ISSUE TITLE
When saving:

### ISSUE THREAD

**Issue by ghost** [preble/InsideJob#7]
Another application has modified this world.

I installed some custom mods, is that the issue? If so, can you fix it so I can use this incredible app?
Thanks!

**Comment by preble** [comment]
You will see this error if another file has opened the level.dat file since Inside Job first opened it.  So if you leave IJ running, you may need to flip to a different world and back to re-open it after another program might have made changes.  Not knowing what mods you have installed and how they work, it's difficult to know whether one of them is poking at the level.dat.  To be sure I'd recommend exiting Minecraft and any of the mods before making changes with IJ.  That will tell you whether something is editing the file while IJ has it open.
